/* 
 * DocuSign Monitor API - v2
 *
 * An API for an integrator to access the features of DocuSign Monitor
 *
 * OpenAPI spec version: v2.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Monitor.Client.SwaggerDateConverter;

namespace DocuSign.Monitor.Model
{
    /// <summary>
    /// CursoredResult
    /// </summary>
    [DataContract]
    public partial class CursoredResult :  IEquatable<CursoredResult>, IValidatableObject
    {
        public CursoredResult()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CursoredResult" /> class.
        /// </summary>
        /// <param name="EndCursor">EndCursor.</param>
        /// <param name="Data">Data.</param>
        public CursoredResult(string EndCursor = default(string), List<Object> Data = default(List<Object>))
        {
            this.EndCursor = EndCursor;
            this.Data = Data;
        }
        
        /// <summary>
        /// Gets or Sets EndCursor
        /// </summary>
        [DataMember(Name="endCursor", EmitDefaultValue=false)]
        public string EndCursor { get; set; }
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<Object> Data { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CursoredResult {\n");
            sb.Append("  EndCursor: ").Append(EndCursor).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CursoredResult);
        }

        /// <summary>
        /// Returns true if CursoredResult instances are equal
        /// </summary>
        /// <param name="other">Instance of CursoredResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CursoredResult other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.EndCursor == other.EndCursor ||
                    this.EndCursor != null &&
                    this.EndCursor.Equals(other.EndCursor)
                ) && 
                (
                    this.Data == other.Data ||
                    this.Data != null &&
                    this.Data.SequenceEqual(other.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.EndCursor != null)
                    hash = hash * 59 + this.EndCursor.GetHashCode();
                if (this.Data != null)
                    hash = hash * 59 + this.Data.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
