/* 
 * Monitor API
 *
 * An API for an integrator to access the features of Docusign Monitor
 *
 * OpenAPI spec version: v3.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Monitor.Model
{
    /// <summary>
    /// StreamResponse
    /// </summary>
    [DataContract]
    public partial class StreamResponse :  IEquatable<StreamResponse>, IValidatableObject
    {
        public StreamResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StreamResponse" /> class.
        /// </summary>
        /// <param name="ResultData">ResultData.</param>
        /// <param name="EndCursor">EndCursor.</param>
        public StreamResponse(List<StreamingEventRow> ResultData = default(List<StreamingEventRow>), string EndCursor = default(string))
        {
            this.ResultData = ResultData;
            this.EndCursor = EndCursor;
        }
        
        /// <summary>
        /// Gets or Sets ResultData
        /// </summary>
        [DataMember(Name="resultData", EmitDefaultValue=false)]
        public List<StreamingEventRow> ResultData { get; set; }
        /// <summary>
        /// Gets or Sets EndCursor
        /// </summary>
        [DataMember(Name="endCursor", EmitDefaultValue=false)]
        public string EndCursor { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamResponse {\n");
            sb.Append("  ResultData: ").Append(ResultData).Append("\n");
            sb.Append("  EndCursor: ").Append(EndCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StreamResponse);
        }

        /// <summary>
        /// Returns true if StreamResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of StreamResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ResultData == other.ResultData ||
                    this.ResultData != null &&
                    this.ResultData.SequenceEqual(other.ResultData)
                ) && 
                (
                    this.EndCursor == other.EndCursor ||
                    this.EndCursor != null &&
                    this.EndCursor.Equals(other.EndCursor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ResultData != null)
                    hash = hash * 59 + this.ResultData.GetHashCode();
                if (this.EndCursor != null)
                    hash = hash * 59 + this.EndCursor.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
