/* 
 * Monitor API
 *
 * An API for an integrator to access the features of Docusign Monitor
 *
 * OpenAPI spec version: v3.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Monitor.Model
{
    /// <summary>
    /// StreamingEventRow
    /// </summary>
    [DataContract]
    public partial class StreamingEventRow :  IEquatable<StreamingEventRow>, IValidatableObject
    {
        public StreamingEventRow()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StreamingEventRow" /> class.
        /// </summary>
        /// <param name="Timestamp">Timestamp.</param>
        /// <param name="EventId">EventId.</param>
        /// <param name="Site">Site.</param>
        /// <param name="AccountId">AccountId.</param>
        /// <param name="OrganizationId">OrganizationId.</param>
        /// <param name="UserId">UserId.</param>
        /// <param name="IntegratorKey">IntegratorKey.</param>
        /// <param name="UserAgent">UserAgent.</param>
        /// <param name="UserAgentClientInfo">UserAgentClientInfo.</param>
        /// <param name="IpAddress">IpAddress.</param>
        /// <param name="IpAddressLocation">IpAddressLocation.</param>
        /// <param name="Object">Object.</param>
        /// <param name="Action">Action.</param>
        /// <param name="Property">Property.</param>
        /// <param name="Field">Field.</param>
        /// <param name="Result">Result.</param>
        /// <param name="Source">Source.</param>
        /// <param name="IsUserMemberOfDomain">IsUserMemberOfDomain.</param>
        /// <param name="ReferencedUserIsMemberOfDomain">ReferencedUserIsMemberOfDomain.</param>
        /// <param name="ReferencedUserId">ReferencedUserId.</param>
        /// <param name="ProxyStatus">ProxyStatus.</param>
        /// <param name="ProxyType">ProxyType.</param>
        /// <param name="ProxyLevel">ProxyLevel.</param>
        /// <param name="Latitude">Latitude.</param>
        /// <param name="Longitude">Longitude.</param>
        /// <param name="City">City.</param>
        /// <param name="State">State.</param>
        /// <param name="Country">Country.</param>
        /// <param name="Device">Device.</param>
        /// <param name="Browser">Browser.</param>
        /// <param name="Os">Os.</param>
        /// <param name="AffectedUserId">AffectedUserId.</param>
        /// <param name="AffectedUserIsMemberOfDomain">AffectedUserIsMemberOfDomain.</param>
        /// <param name="Data">Data.</param>
        public StreamingEventRow(DateTime? Timestamp = default(DateTime?), string EventId = default(string), string Site = default(string), string AccountId = default(string), string OrganizationId = default(string), string UserId = default(string), string IntegratorKey = default(string), string UserAgent = default(string), UserAgentClientInfo UserAgentClientInfo = default(UserAgentClientInfo), string IpAddress = default(string), IpAddressLocation IpAddressLocation = default(IpAddressLocation), string Object = default(string), string Action = default(string), string Property = default(string), string Field = default(string), string Result = default(string), string Source = default(string), bool? IsUserMemberOfDomain = default(bool?), bool? ReferencedUserIsMemberOfDomain = default(bool?), string ReferencedUserId = default(string), string ProxyStatus = default(string), string ProxyType = default(string), string ProxyLevel = default(string), double? Latitude = default(double?), double? Longitude = default(double?), string City = default(string), string State = default(string), string Country = default(string), string Device = default(string), string Browser = default(string), string Os = default(string), string AffectedUserId = default(string), bool? AffectedUserIsMemberOfDomain = default(bool?), Dictionary<string, Object> Data = default(Dictionary<string, Object>))
        {
            this.Timestamp = Timestamp;
            this.EventId = EventId;
            this.Site = Site;
            this.AccountId = AccountId;
            this.OrganizationId = OrganizationId;
            this.UserId = UserId;
            this.IntegratorKey = IntegratorKey;
            this.UserAgent = UserAgent;
            this.UserAgentClientInfo = UserAgentClientInfo;
            this.IpAddress = IpAddress;
            this.IpAddressLocation = IpAddressLocation;
            this.Object = Object;
            this.Action = Action;
            this.Property = Property;
            this.Field = Field;
            this.Result = Result;
            this.Source = Source;
            this.IsUserMemberOfDomain = IsUserMemberOfDomain;
            this.ReferencedUserIsMemberOfDomain = ReferencedUserIsMemberOfDomain;
            this.ReferencedUserId = ReferencedUserId;
            this.ProxyStatus = ProxyStatus;
            this.ProxyType = ProxyType;
            this.ProxyLevel = ProxyLevel;
            this.Latitude = Latitude;
            this.Longitude = Longitude;
            this.City = City;
            this.State = State;
            this.Country = Country;
            this.Device = Device;
            this.Browser = Browser;
            this.Os = Os;
            this.AffectedUserId = AffectedUserId;
            this.AffectedUserIsMemberOfDomain = AffectedUserIsMemberOfDomain;
            this.Data = Data;
        }
        
        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public DateTime? Timestamp { get; set; }
        /// <summary>
        /// Gets or Sets EventId
        /// </summary>
        [DataMember(Name="eventId", EmitDefaultValue=false)]
        public string EventId { get; set; }
        /// <summary>
        /// Gets or Sets Site
        /// </summary>
        [DataMember(Name="site", EmitDefaultValue=false)]
        public string Site { get; set; }
        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name="accountId", EmitDefaultValue=false)]
        public string AccountId { get; set; }
        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name="organizationId", EmitDefaultValue=false)]
        public string OrganizationId { get; set; }
        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public string UserId { get; set; }
        /// <summary>
        /// Gets or Sets IntegratorKey
        /// </summary>
        [DataMember(Name="integratorKey", EmitDefaultValue=false)]
        public string IntegratorKey { get; set; }
        /// <summary>
        /// Gets or Sets UserAgent
        /// </summary>
        [DataMember(Name="userAgent", EmitDefaultValue=false)]
        public string UserAgent { get; set; }
        /// <summary>
        /// Gets or Sets UserAgentClientInfo
        /// </summary>
        [DataMember(Name="userAgentClientInfo", EmitDefaultValue=false)]
        public UserAgentClientInfo UserAgentClientInfo { get; set; }
        /// <summary>
        /// Gets or Sets IpAddress
        /// </summary>
        [DataMember(Name="ipAddress", EmitDefaultValue=false)]
        public string IpAddress { get; set; }
        /// <summary>
        /// Gets or Sets IpAddressLocation
        /// </summary>
        [DataMember(Name="ipAddressLocation", EmitDefaultValue=false)]
        public IpAddressLocation IpAddressLocation { get; set; }
        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [DataMember(Name="object", EmitDefaultValue=false)]
        public string Object { get; set; }
        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public string Action { get; set; }
        /// <summary>
        /// Gets or Sets Property
        /// </summary>
        [DataMember(Name="property", EmitDefaultValue=false)]
        public string Property { get; set; }
        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [DataMember(Name="field", EmitDefaultValue=false)]
        public string Field { get; set; }
        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public string Result { get; set; }
        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name="source", EmitDefaultValue=false)]
        public string Source { get; set; }
        /// <summary>
        /// Gets or Sets IsUserMemberOfDomain
        /// </summary>
        [DataMember(Name="isUserMemberOfDomain", EmitDefaultValue=false)]
        public bool? IsUserMemberOfDomain { get; set; }
        /// <summary>
        /// Gets or Sets ReferencedUserIsMemberOfDomain
        /// </summary>
        [DataMember(Name="referencedUserIsMemberOfDomain", EmitDefaultValue=false)]
        public bool? ReferencedUserIsMemberOfDomain { get; set; }
        /// <summary>
        /// Gets or Sets ReferencedUserId
        /// </summary>
        [DataMember(Name="referencedUserId", EmitDefaultValue=false)]
        public string ReferencedUserId { get; set; }
        /// <summary>
        /// Gets or Sets ProxyStatus
        /// </summary>
        [DataMember(Name="proxyStatus", EmitDefaultValue=false)]
        public string ProxyStatus { get; set; }
        /// <summary>
        /// Gets or Sets ProxyType
        /// </summary>
        [DataMember(Name="proxyType", EmitDefaultValue=false)]
        public string ProxyType { get; set; }
        /// <summary>
        /// Gets or Sets ProxyLevel
        /// </summary>
        [DataMember(Name="proxyLevel", EmitDefaultValue=false)]
        public string ProxyLevel { get; set; }
        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name="latitude", EmitDefaultValue=false)]
        public double? Latitude { get; set; }
        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name="longitude", EmitDefaultValue=false)]
        public double? Longitude { get; set; }
        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [DataMember(Name="city", EmitDefaultValue=false)]
        public string City { get; set; }
        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }
        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }
        /// <summary>
        /// Gets or Sets Device
        /// </summary>
        [DataMember(Name="device", EmitDefaultValue=false)]
        public string Device { get; set; }
        /// <summary>
        /// Gets or Sets Browser
        /// </summary>
        [DataMember(Name="browser", EmitDefaultValue=false)]
        public string Browser { get; set; }
        /// <summary>
        /// Gets or Sets Os
        /// </summary>
        [DataMember(Name="os", EmitDefaultValue=false)]
        public string Os { get; set; }
        /// <summary>
        /// Gets or Sets AffectedUserId
        /// </summary>
        [DataMember(Name="affectedUserId", EmitDefaultValue=false)]
        public string AffectedUserId { get; set; }
        /// <summary>
        /// Gets or Sets AffectedUserIsMemberOfDomain
        /// </summary>
        [DataMember(Name="affectedUserIsMemberOfDomain", EmitDefaultValue=false)]
        public bool? AffectedUserIsMemberOfDomain { get; set; }
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public Dictionary<string, Object> Data { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamingEventRow {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  Site: ").Append(Site).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  IntegratorKey: ").Append(IntegratorKey).Append("\n");
            sb.Append("  UserAgent: ").Append(UserAgent).Append("\n");
            sb.Append("  UserAgentClientInfo: ").Append(UserAgentClientInfo).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  IpAddressLocation: ").Append(IpAddressLocation).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Property: ").Append(Property).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  IsUserMemberOfDomain: ").Append(IsUserMemberOfDomain).Append("\n");
            sb.Append("  ReferencedUserIsMemberOfDomain: ").Append(ReferencedUserIsMemberOfDomain).Append("\n");
            sb.Append("  ReferencedUserId: ").Append(ReferencedUserId).Append("\n");
            sb.Append("  ProxyStatus: ").Append(ProxyStatus).Append("\n");
            sb.Append("  ProxyType: ").Append(ProxyType).Append("\n");
            sb.Append("  ProxyLevel: ").Append(ProxyLevel).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  Browser: ").Append(Browser).Append("\n");
            sb.Append("  Os: ").Append(Os).Append("\n");
            sb.Append("  AffectedUserId: ").Append(AffectedUserId).Append("\n");
            sb.Append("  AffectedUserIsMemberOfDomain: ").Append(AffectedUserIsMemberOfDomain).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StreamingEventRow);
        }

        /// <summary>
        /// Returns true if StreamingEventRow instances are equal
        /// </summary>
        /// <param name="other">Instance of StreamingEventRow to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamingEventRow other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Timestamp == other.Timestamp ||
                    this.Timestamp != null &&
                    this.Timestamp.Equals(other.Timestamp)
                ) && 
                (
                    this.EventId == other.EventId ||
                    this.EventId != null &&
                    this.EventId.Equals(other.EventId)
                ) && 
                (
                    this.Site == other.Site ||
                    this.Site != null &&
                    this.Site.Equals(other.Site)
                ) && 
                (
                    this.AccountId == other.AccountId ||
                    this.AccountId != null &&
                    this.AccountId.Equals(other.AccountId)
                ) && 
                (
                    this.OrganizationId == other.OrganizationId ||
                    this.OrganizationId != null &&
                    this.OrganizationId.Equals(other.OrganizationId)
                ) && 
                (
                    this.UserId == other.UserId ||
                    this.UserId != null &&
                    this.UserId.Equals(other.UserId)
                ) && 
                (
                    this.IntegratorKey == other.IntegratorKey ||
                    this.IntegratorKey != null &&
                    this.IntegratorKey.Equals(other.IntegratorKey)
                ) && 
                (
                    this.UserAgent == other.UserAgent ||
                    this.UserAgent != null &&
                    this.UserAgent.Equals(other.UserAgent)
                ) && 
                (
                    this.UserAgentClientInfo == other.UserAgentClientInfo ||
                    this.UserAgentClientInfo != null &&
                    this.UserAgentClientInfo.Equals(other.UserAgentClientInfo)
                ) && 
                (
                    this.IpAddress == other.IpAddress ||
                    this.IpAddress != null &&
                    this.IpAddress.Equals(other.IpAddress)
                ) && 
                (
                    this.IpAddressLocation == other.IpAddressLocation ||
                    this.IpAddressLocation != null &&
                    this.IpAddressLocation.Equals(other.IpAddressLocation)
                ) && 
                (
                    this.Object == other.Object ||
                    this.Object != null &&
                    this.Object.Equals(other.Object)
                ) && 
                (
                    this.Action == other.Action ||
                    this.Action != null &&
                    this.Action.Equals(other.Action)
                ) && 
                (
                    this.Property == other.Property ||
                    this.Property != null &&
                    this.Property.Equals(other.Property)
                ) && 
                (
                    this.Field == other.Field ||
                    this.Field != null &&
                    this.Field.Equals(other.Field)
                ) && 
                (
                    this.Result == other.Result ||
                    this.Result != null &&
                    this.Result.Equals(other.Result)
                ) && 
                (
                    this.Source == other.Source ||
                    this.Source != null &&
                    this.Source.Equals(other.Source)
                ) && 
                (
                    this.IsUserMemberOfDomain == other.IsUserMemberOfDomain ||
                    this.IsUserMemberOfDomain != null &&
                    this.IsUserMemberOfDomain.Equals(other.IsUserMemberOfDomain)
                ) && 
                (
                    this.ReferencedUserIsMemberOfDomain == other.ReferencedUserIsMemberOfDomain ||
                    this.ReferencedUserIsMemberOfDomain != null &&
                    this.ReferencedUserIsMemberOfDomain.Equals(other.ReferencedUserIsMemberOfDomain)
                ) && 
                (
                    this.ReferencedUserId == other.ReferencedUserId ||
                    this.ReferencedUserId != null &&
                    this.ReferencedUserId.Equals(other.ReferencedUserId)
                ) && 
                (
                    this.ProxyStatus == other.ProxyStatus ||
                    this.ProxyStatus != null &&
                    this.ProxyStatus.Equals(other.ProxyStatus)
                ) && 
                (
                    this.ProxyType == other.ProxyType ||
                    this.ProxyType != null &&
                    this.ProxyType.Equals(other.ProxyType)
                ) && 
                (
                    this.ProxyLevel == other.ProxyLevel ||
                    this.ProxyLevel != null &&
                    this.ProxyLevel.Equals(other.ProxyLevel)
                ) && 
                (
                    this.Latitude == other.Latitude ||
                    this.Latitude != null &&
                    this.Latitude.Equals(other.Latitude)
                ) && 
                (
                    this.Longitude == other.Longitude ||
                    this.Longitude != null &&
                    this.Longitude.Equals(other.Longitude)
                ) && 
                (
                    this.City == other.City ||
                    this.City != null &&
                    this.City.Equals(other.City)
                ) && 
                (
                    this.State == other.State ||
                    this.State != null &&
                    this.State.Equals(other.State)
                ) && 
                (
                    this.Country == other.Country ||
                    this.Country != null &&
                    this.Country.Equals(other.Country)
                ) && 
                (
                    this.Device == other.Device ||
                    this.Device != null &&
                    this.Device.Equals(other.Device)
                ) && 
                (
                    this.Browser == other.Browser ||
                    this.Browser != null &&
                    this.Browser.Equals(other.Browser)
                ) && 
                (
                    this.Os == other.Os ||
                    this.Os != null &&
                    this.Os.Equals(other.Os)
                ) && 
                (
                    this.AffectedUserId == other.AffectedUserId ||
                    this.AffectedUserId != null &&
                    this.AffectedUserId.Equals(other.AffectedUserId)
                ) && 
                (
                    this.AffectedUserIsMemberOfDomain == other.AffectedUserIsMemberOfDomain ||
                    this.AffectedUserIsMemberOfDomain != null &&
                    this.AffectedUserIsMemberOfDomain.Equals(other.AffectedUserIsMemberOfDomain)
                ) && 
                (
                    this.Data == other.Data ||
                    this.Data != null &&
                    this.Data.SequenceEqual(other.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Timestamp != null)
                    hash = hash * 59 + this.Timestamp.GetHashCode();
                if (this.EventId != null)
                    hash = hash * 59 + this.EventId.GetHashCode();
                if (this.Site != null)
                    hash = hash * 59 + this.Site.GetHashCode();
                if (this.AccountId != null)
                    hash = hash * 59 + this.AccountId.GetHashCode();
                if (this.OrganizationId != null)
                    hash = hash * 59 + this.OrganizationId.GetHashCode();
                if (this.UserId != null)
                    hash = hash * 59 + this.UserId.GetHashCode();
                if (this.IntegratorKey != null)
                    hash = hash * 59 + this.IntegratorKey.GetHashCode();
                if (this.UserAgent != null)
                    hash = hash * 59 + this.UserAgent.GetHashCode();
                if (this.UserAgentClientInfo != null)
                    hash = hash * 59 + this.UserAgentClientInfo.GetHashCode();
                if (this.IpAddress != null)
                    hash = hash * 59 + this.IpAddress.GetHashCode();
                if (this.IpAddressLocation != null)
                    hash = hash * 59 + this.IpAddressLocation.GetHashCode();
                if (this.Object != null)
                    hash = hash * 59 + this.Object.GetHashCode();
                if (this.Action != null)
                    hash = hash * 59 + this.Action.GetHashCode();
                if (this.Property != null)
                    hash = hash * 59 + this.Property.GetHashCode();
                if (this.Field != null)
                    hash = hash * 59 + this.Field.GetHashCode();
                if (this.Result != null)
                    hash = hash * 59 + this.Result.GetHashCode();
                if (this.Source != null)
                    hash = hash * 59 + this.Source.GetHashCode();
                if (this.IsUserMemberOfDomain != null)
                    hash = hash * 59 + this.IsUserMemberOfDomain.GetHashCode();
                if (this.ReferencedUserIsMemberOfDomain != null)
                    hash = hash * 59 + this.ReferencedUserIsMemberOfDomain.GetHashCode();
                if (this.ReferencedUserId != null)
                    hash = hash * 59 + this.ReferencedUserId.GetHashCode();
                if (this.ProxyStatus != null)
                    hash = hash * 59 + this.ProxyStatus.GetHashCode();
                if (this.ProxyType != null)
                    hash = hash * 59 + this.ProxyType.GetHashCode();
                if (this.ProxyLevel != null)
                    hash = hash * 59 + this.ProxyLevel.GetHashCode();
                if (this.Latitude != null)
                    hash = hash * 59 + this.Latitude.GetHashCode();
                if (this.Longitude != null)
                    hash = hash * 59 + this.Longitude.GetHashCode();
                if (this.City != null)
                    hash = hash * 59 + this.City.GetHashCode();
                if (this.State != null)
                    hash = hash * 59 + this.State.GetHashCode();
                if (this.Country != null)
                    hash = hash * 59 + this.Country.GetHashCode();
                if (this.Device != null)
                    hash = hash * 59 + this.Device.GetHashCode();
                if (this.Browser != null)
                    hash = hash * 59 + this.Browser.GetHashCode();
                if (this.Os != null)
                    hash = hash * 59 + this.Os.GetHashCode();
                if (this.AffectedUserId != null)
                    hash = hash * 59 + this.AffectedUserId.GetHashCode();
                if (this.AffectedUserIsMemberOfDomain != null)
                    hash = hash * 59 + this.AffectedUserIsMemberOfDomain.GetHashCode();
                if (this.Data != null)
                    hash = hash * 59 + this.Data.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
